# Generated by Django 3.2.7 on 2021-10-01 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210930_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
    ]
